./gwas.filter.sh imputed_ADIPOGen_Adiponectin
./gwas.filter.sh imputed_Astle_et_al_2016_Eosinophil_counts
./gwas.filter.sh imputed_Astle_et_al_2016_Granulocyte_count
./gwas.filter.sh imputed_Astle_et_al_2016_High_light_scatter_reticulocyte_count
./gwas.filter.sh imputed_Astle_et_al_2016_Lymphocyte_counts
./gwas.filter.sh imputed_Astle_et_al_2016_Monocyte_count
./gwas.filter.sh imputed_Astle_et_al_2016_Myeloid_white_cell_count
./gwas.filter.sh imputed_Astle_et_al_2016_Neutrophil_count
./gwas.filter.sh imputed_Astle_et_al_2016_Platelet_count
./gwas.filter.sh imputed_Astle_et_al_2016_Red_blood_cell_count
./gwas.filter.sh imputed_Astle_et_al_2016_Reticulocyte_count
./gwas.filter.sh imputed_Astle_et_al_2016_Sum_basophil_neutrophil_counts
./gwas.filter.sh imputed_Astle_et_al_2016_Sum_eosinophil_basophil_counts
./gwas.filter.sh imputed_Astle_et_al_2016_Sum_neutrophil_eosinophil_counts
./gwas.filter.sh imputed_Astle_et_al_2016_White_blood_cell_count
./gwas.filter.sh imputed_BCAC_ER_negative_BreastCancer_EUR
./gwas.filter.sh imputed_BCAC_ER_positive_BreastCancer_EUR
./gwas.filter.sh imputed_BCAC_Overall_BreastCancer_EUR
./gwas.filter.sh imputed_CARDIoGRAM_C4D_CAD_ADDITIVE
./gwas.filter.sh imputed_CKDGen_Chronic_Kidney_Disease
./gwas.filter.sh imputed_CNCR_Insomnia_all
./gwas.filter.sh imputed_DIAGRAM_T2D_TRANS_ETHNIC
./gwas.filter.sh imputed_EAGLE_Eczema
./gwas.filter.sh imputed_EGG_BL
./gwas.filter.sh imputed_EGG_BMI_HapMapImputed
./gwas.filter.sh imputed_EGG_BW3_EUR
./gwas.filter.sh imputed_EGG_Pubertal_growth_10F
./gwas.filter.sh imputed_EGG_Pubertal_growth_12M
./gwas.filter.sh imputed_ENIGMA_Intracraneal_Volume
./gwas.filter.sh imputed_GABRIEL_Asthma
./gwas.filter.sh imputed_GEFOS_Forearm
./gwas.filter.sh imputed_GIANT_2015_BMI_EUR
./gwas.filter.sh imputed_GIANT_2017_BMI_Active_EUR
./gwas.filter.sh imputed_GIANT_HEIGHT
./gwas.filter.sh imputed_GIANT_HIP_Combined_EUR
./gwas.filter.sh imputed_GIANT_WC_Combined_EUR
./gwas.filter.sh imputed_GIANT_WHR_Combined_EUR
./gwas.filter.sh imputed_GLGC_Mc_HDL
./gwas.filter.sh imputed_GLGC_Mc_LDL
./gwas.filter.sh imputed_GLGC_Mc_TG
./gwas.filter.sh imputed_GPC-NEO-NEUROTICISM
./gwas.filter.sh imputed_HRGene_HeartRate
./gwas.filter.sh imputed_IBD.EUR.Crohns_Disease
./gwas.filter.sh imputed_IBD.EUR.Inflammatory_Bowel_Disease
./gwas.filter.sh imputed_IBD.EUR.Ulcerative_Colitis
./gwas.filter.sh imputed_ICBP_DiastolicPressure
./gwas.filter.sh imputed_ICBP_SystolicPressure
./gwas.filter.sh imputed_IGAP_Alzheimer
./gwas.filter.sh imputed_ILAE_Genetic_generalised_epilepsy
./gwas.filter.sh imputed_IMMUNOBASE_Celiac_disease_hg19
./gwas.filter.sh imputed_IMMUNOBASE_Multiple_sclerosis_hg19
./gwas.filter.sh imputed_IMMUNOBASE_Systemic_lupus_erythematosus_hg19
./gwas.filter.sh imputed_ISGC_Malik_2016_METASTROKE_all_strokes
./gwas.filter.sh imputed_Jones_et_al_2016_Chronotype
./gwas.filter.sh imputed_Jones_et_al_2016_SleepDuration
./gwas.filter.sh imputed_MAGIC_FastingGlucose
./gwas.filter.sh imputed_MAGIC_ln_FastingInsulin
./gwas.filter.sh imputed_MAGNETIC_CH2.DB.ratio
./gwas.filter.sh imputed_MAGNETIC_HDL.C
./gwas.filter.sh imputed_MAGNETIC_IDL.TG
./gwas.filter.sh imputed_MAGNETIC_LDL.C
./gwas.filter.sh imputed_PGC_ADHD_EUR_2017
./gwas.filter.sh imputed_PGC_ASD_2017_CEU
./gwas.filter.sh imputed_RA_OKADA_TRANS_ETHNIC
./gwas.filter.sh imputed_SSGAC_Depressive_Symptoms
./gwas.filter.sh imputed_SSGAC_Education_Years_Pooled
./gwas.filter.sh imputed_TAGC_Asthma_EUR
./gwas.filter.sh imputed_UKB_1160_Sleep_duration
./gwas.filter.sh imputed_UKB_1180_Morning_or_evening_person_chronotype
./gwas.filter.sh imputed_UKB_1200_Sleeplessness_or_insomnia
./gwas.filter.sh imputed_UKB_1807_Fathers_age_at_death
./gwas.filter.sh imputed_UKB_20002_1065_self_reported_hypertension
./gwas.filter.sh imputed_UKB_20002_1094_self_reported_deep_venous_thrombosis_dvt
./gwas.filter.sh imputed_UKB_20002_1111_self_reported_asthma
./gwas.filter.sh imputed_UKB_20002_1154_self_reported_irritable_bowel_syndrome
./gwas.filter.sh imputed_UKB_20002_1222_self_reported_type_1_diabetes
./gwas.filter.sh imputed_UKB_20002_1223_self_reported_type_2_diabetes
./gwas.filter.sh imputed_UKB_20002_1225_self_reported_hyperthyroidism_or_thyrotoxicosis
./gwas.filter.sh imputed_UKB_20002_1226_self_reported_hypothyroidism_or_myxoedema
./gwas.filter.sh imputed_UKB_20002_1243_self_reported_psychological_or_psychiatric_problem
./gwas.filter.sh imputed_UKB_20002_1261_self_reported_multiple_sclerosis
./gwas.filter.sh imputed_UKB_20002_1262_self_reported_parkinsons_disease
./gwas.filter.sh imputed_UKB_20002_1265_self_reported_migraine
./gwas.filter.sh imputed_UKB_20002_1289_self_reported_schizophrenia
./gwas.filter.sh imputed_UKB_20002_1309_self_reported_osteoporosis
./gwas.filter.sh imputed_UKB_20002_1313_self_reported_ankylosing_spondylitis
./gwas.filter.sh imputed_UKB_20002_1452_self_reported_eczema_or_dermatitis
./gwas.filter.sh imputed_UKB_20002_1453_self_reported_psoriasis
./gwas.filter.sh imputed_UKB_20002_1461_self_reported_inflammatory_bowel_disease
./gwas.filter.sh imputed_UKB_20002_1462_self_reported_crohns_disease
./gwas.filter.sh imputed_UKB_20002_1463_self_reported_ulcerative_colitis
./gwas.filter.sh imputed_UKB_20002_1464_self_reported_rheumatoid_arthritis
./gwas.filter.sh imputed_UKB_20002_1466_self_reported_gout
./gwas.filter.sh imputed_UKB_20002_1473_self_reported_high_cholesterol
./gwas.filter.sh imputed_UKB_20002_1616_self_reported_insomnia
./gwas.filter.sh imputed_UKB_20016_Fluid_intelligence_score
./gwas.filter.sh imputed_UKB_20022_Birth_weight
./gwas.filter.sh imputed_UKB_20127_Neuroticism_score
./gwas.filter.sh imputed_UKB_21001_Body_mass_index_BMI
./gwas.filter.sh imputed_UKB_23099_Body_fat_percentage
./gwas.filter.sh imputed_UKB_2395_2_Hair_or_balding_pattern_Pattern_2
./gwas.filter.sh imputed_UKB_2395_3_Hair_or_balding_pattern_Pattern_3
./gwas.filter.sh imputed_UKB_2395_4_Hair_or_balding_pattern_Pattern_4
./gwas.filter.sh imputed_UKB_3526_Mothers_age_at_death
./gwas.filter.sh imputed_UKB_50_Standing_height
./gwas.filter.sh imputed_UKB_6150_1_Vascular_or_heart_problems_diagnosed_by_doctor_Heart_attack
./gwas.filter.sh imputed_UKB_6152_5_diagnosed_by_doctor_Blood_clot_in_the_leg_DVT
./gwas.filter.sh imputed_UKB_6152_7_diagnosed_by_doctor_Blood_clot_in_the_lung
./gwas.filter.sh imputed_UKB_6152_8_diagnosed_by_doctor_Asthma
./gwas.filter.sh imputed_UKB_6152_9_diagnosed_by_doctor_Hayfever_allergic_rhinitis_or_eczema
./gwas.filter.sh imputed_UKB_G40_Diagnoses_main_ICD10_G40_Epilepsy
./gwas.filter.sh imputed_UKB_G43_Diagnoses_main_ICD10_G43_Migraine
./gwas.filter.sh imputed_pgc.scz2
./gwas.filter.sh imputed_tag.evrsmk.tbl
