python mapGene2Trait.py imputed_variants/imputed_ADIPOGen_Adiponectin.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Eosinophil_counts.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Granulocyte_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_High_light_scatter_reticulocyte_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Lymphocyte_counts.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Monocyte_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Myeloid_white_cell_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Neutrophil_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Platelet_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Red_blood_cell_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Reticulocyte_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Sum_basophil_neutrophil_counts.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Sum_eosinophil_basophil_counts.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_Sum_neutrophil_eosinophil_counts.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Astle_et_al_2016_White_blood_cell_count.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_BCAC_ER_negative_BreastCancer_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_BCAC_ER_positive_BreastCancer_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_BCAC_Overall_BreastCancer_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_CARDIoGRAM_C4D_CAD_ADDITIVE.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_CKDGen_Chronic_Kidney_Disease.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_CNCR_Insomnia_all.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_DIAGRAM_T2D_TRANS_ETHNIC.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_EAGLE_Eczema.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_EGG_BL.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_EGG_BMI_HapMapImputed.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_EGG_BW3_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_EGG_Pubertal_growth_10F.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_EGG_Pubertal_growth_12M.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_ENIGMA_Intracraneal_Volume.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GABRIEL_Asthma.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GEFOS_Forearm.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GIANT_2015_BMI_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GIANT_2017_BMI_Active_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GIANT_HEIGHT.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GIANT_HIP_Combined_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GIANT_WC_Combined_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GIANT_WHR_Combined_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GLGC_Mc_HDL.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GLGC_Mc_LDL.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GLGC_Mc_TG.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_GPC-NEO-NEUROTICISM.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_HRGene_HeartRate.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_IBD.EUR.Crohns_Disease.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_IBD.EUR.Inflammatory_Bowel_Disease.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_IBD.EUR.Ulcerative_Colitis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_ICBP_DiastolicPressure.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_ICBP_SystolicPressure.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_IGAP_Alzheimer.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_ILAE_Genetic_generalised_epilepsy.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_IMMUNOBASE_Celiac_disease_hg19.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_IMMUNOBASE_Multiple_sclerosis_hg19.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_IMMUNOBASE_Systemic_lupus_erythematosus_hg19.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_ISGC_Malik_2016_METASTROKE_all_strokes.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Jones_et_al_2016_Chronotype.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_Jones_et_al_2016_SleepDuration.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_MAGIC_FastingGlucose.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_MAGIC_ln_FastingInsulin.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_MAGNETIC_CH2.DB.ratio.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_MAGNETIC_HDL.C.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_MAGNETIC_IDL.TG.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_MAGNETIC_LDL.C.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_PGC_ADHD_EUR_2017.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_PGC_ASD_2017_CEU.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_RA_OKADA_TRANS_ETHNIC.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_SSGAC_Depressive_Symptoms.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_SSGAC_Education_Years_Pooled.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_TAGC_Asthma_EUR.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_1160_Sleep_duration.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_1180_Morning_or_evening_person_chronotype.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_1200_Sleeplessness_or_insomnia.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_1807_Fathers_age_at_death.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1065_self_reported_hypertension.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1094_self_reported_deep_venous_thrombosis_dvt.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1111_self_reported_asthma.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1154_self_reported_irritable_bowel_syndrome.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1222_self_reported_type_1_diabetes.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1223_self_reported_type_2_diabetes.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1225_self_reported_hyperthyroidism_or_thyrotoxicosis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1226_self_reported_hypothyroidism_or_myxoedema.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1243_self_reported_psychological_or_psychiatric_problem.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1261_self_reported_multiple_sclerosis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1262_self_reported_parkinsons_disease.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1265_self_reported_migraine.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1289_self_reported_schizophrenia.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1309_self_reported_osteoporosis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1313_self_reported_ankylosing_spondylitis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1452_self_reported_eczema_or_dermatitis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1453_self_reported_psoriasis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1461_self_reported_inflammatory_bowel_disease.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1462_self_reported_crohns_disease.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1463_self_reported_ulcerative_colitis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1464_self_reported_rheumatoid_arthritis.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1466_self_reported_gout.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1473_self_reported_high_cholesterol.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20002_1616_self_reported_insomnia.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20016_Fluid_intelligence_score.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20022_Birth_weight.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_20127_Neuroticism_score.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_21001_Body_mass_index_BMI.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_23099_Body_fat_percentage.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_2395_2_Hair_or_balding_pattern_Pattern_2.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_2395_3_Hair_or_balding_pattern_Pattern_3.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_2395_4_Hair_or_balding_pattern_Pattern_4.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_3526_Mothers_age_at_death.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_50_Standing_height.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_6150_1_Vascular_or_heart_problems_diagnosed_by_doctor_Heart_attack.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_6152_5_diagnosed_by_doctor_Blood_clot_in_the_leg_DVT.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_6152_7_diagnosed_by_doctor_Blood_clot_in_the_lung.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_6152_8_diagnosed_by_doctor_Asthma.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_6152_9_diagnosed_by_doctor_Hayfever_allergic_rhinitis_or_eczema.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_G40_Diagnoses_main_ICD10_G40_Epilepsy.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_UKB_G43_Diagnoses_main_ICD10_G43_Migraine.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_pgc.scz2.filtered.txt >> GWAS.genes.v8.csv
python mapGene2Trait.py imputed_variants/imputed_tag.evrsmk.tbl.filtered.txt >> GWAS.genes.v8.csv
